apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blackbox-exporter.fullname" . }}
  labels:
    {{- include "blackbox-exporter.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.config | default "{}" | nindent 4 }}
