{{- if .Values.useDaemonSet }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "blackbox-exporter.fullname" . }}
  labels:
    {{- include "blackbox-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "blackbox-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blackbox-exporter.labels" . | nindent 8 }}
    spec:
      containers:
        - name: blackbox
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.config }}
          args: ["--config.file=/config/config.yml"]
          {{- end }}
          ports:
            - containerPort: 9115
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.config }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.config }}
      volumes:
        - name: config
          configMap:
            name: {{ include "blackbox-exporter.fullname" . }}
    {{- end }}
{{- end }}
