apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldap-search-exporter.fullname" . }}
  labels:
    {{- include "ldap-search-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "ldap-search-exporter.selectorLabels" . | nindent 4 }}
