## Container image
image:
  repository: prom/blackbox-exporter
  tag: v0.25.0
  pullPolicy: IfNotPresent

## Node labels for pod assigment
nodeSelector: {}

# Use a Deployment or a DeamonSet
useDaemonSet: false

## Configuration (module, ...)
config: {}
#  modules:
#    http_2xx:
#      prober: http
#      timeout: 5s
#      http:
