apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpd-ldapauth-proxy.fullname" . }}
  labels:
    {{- include "httpd-ldapauth-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "httpd-ldapauth-proxy.selectorLabels" . | nindent 4 }}
