{{- if not .Values.puppetConfDir }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "puppetserver.fullname" . }}-user-confdir
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  puppet.conf: |
    [main]
    ssldir = /etc/puppetlabs/puppet/ssl
    server = {{ include "puppetserver.fullname" . }}
{{- end }}
{{- if not .Values.puppetserverConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "puppetserver.fullname" . }}-puppetserver
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  ca.conf: |
{{ .Values.ca_conf | indent 4 }}
  auth.conf: |
{{ .Values.auth_conf | indent 4 }}
  logback.xml: |
    <configuration scan="true">
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
        </appender>

        <logger name="org.eclipse.jetty" level="INFO"/>
        <logger name="com.puppetlabs.puppetserver.LoggingPuppetProfiler" level="INFO"/>

        <root level="info">
            <appender-ref ref="STDOUT"/>
        </root>
    </configuration>
  request-logging.xml: |
    <configuration debug="false" scan="true">
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="net.logstash.logback.encoder.AccessEventCompositeJsonEncoder">
                <providers>
                    <version/>
                    <pattern>
                        <pattern>
                            {
                              "@timestamp":"%date{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}",
                              "clientip":"%remoteIP",
                              "auth":"%user",
                              "verb":"%requestMethod",
                              "requestprotocol":"%protocol",
                              "rawrequest":"%requestURL",
                              "response":"#asLong{%statusCode}",
                              "bytes":"#asLong{%bytesSent}",
                              "total_service_time":"#asLong{%elapsedTime}",
                              "request":"http://%header{Host}%requestURI",
                              "referrer":"%header{Referer}",
                              "agent":"%header{User-agent}",

                              "request.host":"%header{Host}",
                              "request.accept":"%header{Accept}",
                              "request.accept-encoding":"%header{Accept-Encoding}",
                              "request.connection":"%header{Connection}",

                              "puppet.client-verify":"%header{X-Client-Verify}",
                              "puppet.client-dn":"%header{X-Client-DN}",
                              "puppet.client-cert":"%header{X-Client-Cert}",

                              "response.content-type":"%responseHeader{Content-Type}",
                              "response.content-length":"%responseHeader{Content-Length}",
                              "response.server":"%responseHeader{Server}",
                              "response.connection":"%responseHeader{Connection}"
                            }
                        </pattern>
                    </pattern>
                </providers>
            </encoder>
        </appender>

        <appender-ref ref="STDOUT"/>
    </configuration>
{{- end }}
{{- if not .Values.puppetConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "puppetserver.fullname" . }}-puppet
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  puppet.conf: |
{{ .Values.puppet_conf | indent 4 }}
  hiera.yaml: |
    ---
    version: 5
  autosign: |
{{ .Values.autosign.script | indent 4 }}
  puppetdb.conf: |
{{ .Values.puppetdb_conf | indent 4 }}
  routes.yaml: |
{{ .Values.routes_yaml | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "puppetserver.fullname" . }}-jmx-exporter
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: |-
    ---
    whitelistObjectNames:
      - puppetserver:name=puppetlabs.localhost.compiler.compile
      - puppetserver:name=puppetlabs.localhost.compiler.find_node
      - puppetserver:name=puppetlabs.localhost.compiler.find_facts
      - puppetserver:name=puppetlabs.localhost.functions
      - puppetserver:name=puppetlabs.localhost.jruby.num-jrubies
      - puppetserver:name=puppetlabs.localhost.jruby.num-free-jrubies
      - puppetserver:name=puppetlabs.localhost.jruby.free-jrubies-histo
      - puppetserver:name=puppetlabs.localhost.jruby.requested-jrubies-histo
      - puppetserver:name=puppetlabs.localhost.memory.heap.used
      - puppetserver:name=puppetlabs.localhost.memory.non-heap.used
      - puppetserver:name=puppetlabs.localhost.num-cpus
      - puppetserver:name=puppetlabs.localhost.jruby.borrow-timer
      - puppetserver:name=puppetlabs.localhost.jruby.wait-timer
      - puppetserver:name=puppetlabs.localhost.jruby.lock-held-timer
      - puppetserver:name=puppetlabs.localhost.jruby.lock-wait-timer
      - puppetserver:name=puppetlabs.localhost.http-client.experimental.with-metric-id.puppetdb.command.full-response
      - puppetserver:name=puppetlabs.localhost.http-client.experimental.with-metric-id.puppetdb.command.replace_catalog.full-response
      - puppetserver:name=puppetlabs.localhost.http-client.experimental.with-metric-id.puppetdb.command.replace_facts.full-response
      - puppetserver:name=puppetlabs.localhost.http-client.experimental.with-metric-id.puppetdb.command.store_report.full-response
      - puppetserver:name=puppetlabs.localhost.http-client.experimental.with-metric-id.puppetdb.facts.find.full-response
      - puppetserver:name=puppetlabs.localhost.http-client.experimental.with-metric-id.puppetdb.facts.full-response
      - puppetserver:name=puppetlabs.localhost.http-client.experimental.with-metric-id.puppetdb.full-response
      - puppetserver:name=puppetlabs.localhost.http-client.experimental.with-metric-id.puppetdb.resource.full-response
      - puppetserver:name=puppetlabs.localhost.http-client.experimental.with-metric-id.puppetdb.resource.search.full-response
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-catalog-/\*/-requests"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-report-/\*/-requests"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-node-/\*/-requests"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-file_metadatas-/\*/-requests"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-file_metadata-/\*/-requests"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-file_content-/\*/-requests"
      - puppetserver:name=puppetlabs.localhost.http.other-requests
      - puppetserver:name=puppetlabs.localhost.http.total-requests
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-catalog-/\*/-percentage"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-report-/\*/-percentage"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-node-/\*/-percentage"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-file_metadatas-/\*/-percentage"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-file_metadata-/\*/-percentage"
      - puppetserver:name="puppetlabs.localhost.http.puppet-v3-file_content-/\*/-percentage"
      - puppetserver:name=puppetlabs.localhost.http.active-requests
      - puppetserver:name=puppetlabs.localhost.http.active-histo
