{
 "title": "Puppet Server",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter", "query": "${VAR_FILTER}" }
  ]
 },
 "panels": [
  { "title": "Puppetserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compilation",
   "type": "graph",
   "description": "Time spent in different parts of handling a Catalog request\n\n* `compile`: time to compile catalogs.\n* `static_compile`: time to do a static compile of catalogs.\n* `static compile postprocessing`: time to do postprocessing of static catalog, including inlining file metadata.\n* `function calls`: time spent calling functions (included in `compile` time)\n* `find_node`: time to get node object (not included in `compile` time)\n* `find_facts`: time to parse facts sent as part of catalog request (not included in `compile` time)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "puppetserver_puppetlabs_localhost_compiler_compile_Mean",
     "legendFormat": "compile",
     "target": "alias(puppetlabs.master.example.com.compiler.compile.mean,'compile')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_functions_Mean",
     "legendFormat": "function calls",
     "target": "alias(puppetlabs.master.example.com.functions.mean,'function calls')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_compiler_find_node_Mean",
     "legendFormat": "find_node",
     "target": "alias(puppetlabs.master.example.com.compiler.find_node.mean,'find_node')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_compiler_static_compile_Mean",
     "legendFormat": "static compile",
     "target": "alias(puppetlabs.master.example.com.compiler.static_compile.mean,'static compile')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_compiler_static_compile_processing_Mean",
     "legendFormat": "static compile postprocessing",
     "target": "alias(puppetlabs.master.example.com.compiler.static_compile_postprocessing.mean,'static compile postprocessing')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_compiler_find_facts_Mean",
     "legendFormat": "find_facts",
     "target": "alias(puppetlabs.master.example.com.compiler.find_facts.mean,'find_facts')"
    }
   ]
  },
  {
   "title": "JRuby Usage",
   "type": "graph",
   "description": "* `num jrubies`: number of JRuby instances (constant)\n* `num free jrubies`: number of JRuby instances free\n* `average free jrubies`: average free JRubies over time\n* `average requested jrubies`: average requested JRubies over time",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppetserver_puppetlabs_localhost_jruby_num_jrubies_Value",
     "legendFormat": "num jrubies",
     "target": "alias(puppetlabs.master.example.com.jruby.num-jrubies,'num jrubies')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_jruby_num_free_jrubies_Value",
     "legendFormat": "num free jrubies",
     "target": "alias(puppetlabs.master.example.com.jruby.num-free-jrubies,'num free jrubies')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_jruby_free_jrubies_histo_Mean",
     "legendFormat": "average free jrubies",
     "target": "alias(puppetlabs.master.example.com.jruby.free-jrubies-histo.mean,'average free jrubies')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_jruby_requested_jrubies_histo_Mean",
     "legendFormat": "average requested jrubies",
     "target": "alias(puppetlabs.master.example.com.jruby.requested-jrubies-histo.mean,'average requested jrubies')"
    }
   ]
  },
  {
   "title": "JVM metrics",
   "type": "graph",
   "description": "Heap and non-heap memory used, number of cpus available.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "puppetserver_puppetlabs_localhost_memory_heap_used_Value",
     "legendFormat": "heap used",
     "target": "alias(puppetlabs.master.example.com.memory.heap.used,'heap used')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_memory_non_heap_used_Value",
     "legendFormat": "non-heap used",
     "target": "alias(puppetlabs.master.example.com.memory.non-heap.used,'non-heap used')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_num_cpus_Value",
     "legendFormat": "num cpus",
     "target": "alias(puppetlabs.master.example.com.num-cpus, 'num cpus')"
    }
   ]
  },
  {
   "title": "Request Durations",
   "type": "graph",
   "description": "Average request time by type - time the server spends serving each type of request, including time waiting to acquire a JRuby",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_catalog_requests_Mean",
     "legendFormat": "catalog",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-catalog-.*.-requests.mean,'catalog')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_report_requests_Mean",
     "legendFormat": "report",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-report-.*.-requests.mean,'report')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_node_requests_Mean",
     "legendFormat": "node",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-node-.*.-requests.mean,'node')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_file_metadatas_requests_Mean",
     "legendFormat": "file_metadatas",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-file_metadatas-.*.-requests.mean,'file_metadatas')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_file_metadata_requests_Mean",
     "legendFormat": "file_metadata",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-file_metadata-.*.-requests.mean,'file_metadata')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_file_content_requests_Mean",
     "legendFormat": "file_content",
     "target": "alias(puppetlabs.master.example.com.http.puppet-v3-file_content-.*.-requests.mean,'file_content')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_other_requests_Mean",
     "legendFormat": "other",
     "target": "alias(puppetlabs.master.example.com.http.other-requests.mean,'other')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_total_requests_Mean",
     "legendFormat": "all",
     "target": "alias(puppetlabs.master.example.com.http.total-requests.mean,'all')"
    }
   ]
  },
  {
   "title": "JRuby Pool Timers",
   "type": "graph",
   "description": "* `borrow time`: average time a JRuby is borrowed for\n* `wait time`: average time Puppet Server spends waiting to borrow a JRuby to service a request\n* `lock held time`: average time the lock on the JRuby pool is held\n* `lock wait time`: average time Puppet Server spends waiting to acquire the lock",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "puppetserver_puppetlabs_localhost_jruby_borrow_timer_Mean",
     "legendFormat": "borrow time",
     "target": "alias(puppetlabs.master.example.com.jruby.borrow-timer.mean,'borrow time')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_jruby_wait_timer_Mean",
     "legendFormat": "wait time",
     "target": "alias(puppetlabs.master.example.com.jruby.wait-timer.mean,'wait time')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_jruby_lock_held_timer_Mean",
     "legendFormat": "lock held time",
     "target": "alias(puppetlabs.master.example.com.jruby.lock-held-timer.mean,'lock held time')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_jruby_lock_wait_timer_Mean",
     "legendFormat": "lock wait time",
     "target": "alias(puppetlabs.master.example.com.jruby.lock-wait-timer.mean,'lock wait time')"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "description": "Puppetserver Garbage Collection rates on 1 minute",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Mean time per GC" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"puppetserver\"}[1m])/rate(jvm_gc_collection_seconds_count{job=\"puppetserver\"}[1m])",
     "legendFormat": "time per request {{gc}}"
    },
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"puppetserver\"}[1m])",
     "legendFormat": "rate {{gc}}"
    }
   ]
  },
  {
   "title": "Request Ratios",
   "type": "graph",
   "description": "Percentage of requests handled of each type.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent", "label": "Percentage of Requests" }
   ],
   "targets": [
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_catalog_percentage_Value * 100",
     "legendFormat": "catalog",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-catalog-.*.-percentage,100),'catalog')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_report_percentage_Value * 100",
     "legendFormat": "report",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-report-.*.-percentage,100),'report')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_node_percentage_Value * 100",
     "legendFormat": "node",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-node-.*.-percentage,100),'node')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_file_metadatas_percentage_Value * 100",
     "legendFormat": "file_metadatas",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-file_metadatas-.*.-percentage,100),'file_metadatas')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_file_metadata_percentage_Value * 100",
     "legendFormat": "file_metadata",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-file_metadata-.*.-percentage,100),'file_metadata')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_puppet_v3_file_content_percentage_Value * 100",
     "legendFormat": "file_content",
     "target": "alias(scale(puppetlabs.master.example.com.http.puppet-v3-file_content-.*.-percentage,100),'file_content')"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "description": "Number of active requests and average number of active requests (over ~ 5 minutes).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppetserver_puppetlabs_localhost_http_active_requests_Count",
     "legendFormat": "active requests",
     "target": "alias(puppetlabs.master.example.com.http.active-requests.count,'active requests')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_active_histo_Mean",
     "legendFormat": "average number of active requests",
     "target": "alias(puppetlabs.master.example.com.http.active-histo.mean, 'average number of active requests')"
    }
   ]
  },
  {
   "title": "External HTTP Communications",
   "type": "graph",
   "description": "Time to make HTTP requests to other services\n\n* `PuppetDB: replace facts`: time to send a \"facts replace\" command to PuppetDB (part of a catalog compile)\n* `PuppetDB: replace catalog`: time to send a \"catalog replace\" command to PuppetDB (part of a catalog compile)\n* `PuppetDB: store report`: time to send a \"report store\" command to PuppetDB (part of handling a report request)\n* `PuppetDB: find facts`: time to get facts from PuppetDB (part of a node and catalog request, if the facts for the node are not cached)\n* `PuppetDB: search resources`: time to get exported resources from PuppetDB (part of a catalog compile if exported resources are used)\n*`PuppetDB: query`: time to execute a PuppetDB query (part of a catalog compile if the puppetdb query function is used)\n* `Http report processor`: time to submit a report to the http report url (if the http report processor is used)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "puppetserver_puppetlabs_localhost_http_client_experimental_with_metric_id_puppetdb_command_replace_facts_full_response_Mean",
     "legendFormat": "PuppetDB: replace facts",
     "target": "alias(puppetlabs.master.example.com.http-client.experimental.with-metric-id.puppetdb.command.replace_facts.full-response.mean, 'PuppetDB: replace facts')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_client_experimental_with_metric_id_puppetdb_command_replace_catalog_full_response_Mean",
     "legendFormat": "PuppetDB: replace catalog",
     "target": "alias(puppetlabs.master.example.com.http-client.experimental.with-metric-id.puppetdb.command.replace_catalog.full-response.mean, 'PuppetDB: replace catalog')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_client_experimental_with_metric_id_puppetdb_command_store_report_full_response_Mean",
     "legendFormat": "PuppetDB: store report",
     "target": "alias(puppetlabs.master.example.com.http-client.experimental.with-metric-id.puppetdb.command.store_report.full-response.mean, 'PuppetDB: store report')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_client_experimental_with_metric_id_puppetdb_facts_find_full_response_Mean",
     "legendFormat": "PuppetDB: find facts",
     "target": "alias(puppetlabs.master.example.com.http-client.experimental.with-metric-id.puppetdb.facts.find.full-response.mean, 'PuppetDB: find facts')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_client_experimental_with_metric_id_puppetdb_resource_search_full_response_Mean",
     "legendFormat": "PuppetDB: search resources",
     "target": "alias(puppetlabs.master.example.com.http-client.experimental.with-metric-id.puppetdb.resource.search.full-response.mean, 'PuppetDB: search resources')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_client_experimental_with_metric_id_puppetdb_query_full_response_Mean",
     "legendFormat": "PuppetDB: query",
     "target": "alias(puppetlabs.master.example.com.http-client.experimental.with-metric-id.puppetdb.query.full-response.mean, 'PuppetDB: query')"
    },
    {
     "expr": "puppetserver_puppetlabs_localhost_http_client_experimental_with_metric_id_puppet_report_http_full_response_Mean",
     "legendFormat": "Http report processor",
     "target": "alias(puppetlabs.master.example.com.http-client.experimental.with-metric-id.puppet.report.http.full-response.mean, 'Http report processor')"
    }
   ]
  },
  { "title": "PuppetDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "PuppetDB JVM metrics",
   "type": "graph",
   "description": "Heap and non-heap memory used, number of cpus available.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=\"puppetdb\"}\t",
     "legendFormat": "heap used"
    },
    {
     "expr": "java_lang_Memory_NonHeapMemoryUsage_used{job=\"puppetdb\"}\t",
     "legendFormat": "non-heap used"
    },
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{job=\"puppetdb\"}",
     "legendFormat": "num cpus"
    }
   ]
  },
  {
   "title": "Write Pool DB Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppetlabs_puppetdb_database_PDBWritePool_pool_ActiveConnections_Value",
     "legendFormat": "Active connections"
    },
    {
     "expr": "puppetlabs_puppetdb_database_PDBWritePool_pool_IdleConnections_Value",
     "legendFormat": "Idle connections"
    },
    {
     "expr": "puppetlabs_puppetdb_database_PDBWritePool_pool_PendingConnections_Value",
     "legendFormat": "Pending threads"
    }
   ]
  },
  {
   "title": "Read Pool DB Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "puppetlabs_puppetdb_database_PDBReadPool_pool_ActiveConnections_Value",
     "legendFormat": "Active connections"
    },
    {
     "expr": "puppetlabs_puppetdb_database_PDBReadPool_pool_IdleConnections_Value",
     "legendFormat": "Idle connections"
    },
    {
     "expr": "puppetlabs_puppetdb_database_PDBReadPool_pool_PendingConnections_Value",
     "legendFormat": "Pending threads"
    }
   ]
  },
  {
   "title": "Population",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(puppetlabs_puppetdb_population_num_nodes_Value)"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(puppetlabs_puppetdb_population_num_resources_Value)"
    }
   ]
  },
  {
   "title": "Average resources per node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(puppetlabs_puppetdb_population_avg_resources_per_node_Value)"
    }
   ]
  },
  {
   "title": "Percentage of resource duplication",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(puppetlabs_puppetdb_population_pct_resource_dupes_Value)"
    }
   ]
  }
 ]
}