---
{{- if .Values.gnupg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "puppetserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetserver.name" . }}
    helm.sh/chart: {{ include "puppetserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  gpg.asc: |
{{ .Values.gnupg.private | indent 4 }}
  autosign_psk: {{ .Values.autosign.psk | quote }}
{{- end }}
