{{- if ( or ( and ( .Values.ldap ) ( .Values.ldap.ldaps ) ) ( and ( .Values.freeipa ) ( .Values.freeipa.ca ) ) ) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "freeipa-proxy-ha.fullname" . }}
  labels:
    app: {{ template "freeipa-proxy-ha.name" . }}
    chart: {{ template "freeipa-proxy-ha.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{-   if ( and ( not .Values.ldap.ldaps.existingSecret ) ( .Values.ldap.ldaps.cert ) ( .Values.ldap.ldaps.key ) ) }}
  key.pem: {{ .Values.ldap.ldaps.key | b64enc }}
  cert.pem: {{ .Values.ldap.ldaps.cert | b64enc }}
{{-   end }}
{{-   if ( and ( .Values.freeipa ) ( .Values.freeipa.ca ) ) }}
  ca.pem: {{ .Values.freeipa.ca | b64enc }}
{{-   end -}}
{{- end -}}
