{{ if .Values.kafkaTlsAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-kafka-auth
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  key.pem: {{ required "kafkaTlsAuth hash must contain 'key' entry" .Values.kafkaTlsAuth.key | b64enc | quote }}
  cert.pem: {{ required "kafkaTlsAuth hash must contain 'cert' entry" .Values.kafkaTlsAuth.cert | b64enc | quote }}
  ca.pem:  {{ required "kafkaTlsAuth hash must contain 'ca' entry" .Values.kafkaTlsAuth.ca | b64enc | quote }}
{{ end }}
