---
{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraboard.fullname" . }}
  labels:
{{ include "terraboard.labels" . | indent 4 }}
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.key_id | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret_access_key | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
{{- end -}}
