apiVersion: v1
kind: Service
metadata:
  name: {{ include "puppetdb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetdb.name" . }}
    helm.sh/chart: {{ include "puppetdb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.puppetdb.service.type }}
  ports:
    - port: {{ .Values.puppetdb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9080
      targetPort: metrics
      protocol: TCP
      name: metrics

  selector:
    app.kubernetes.io/name: {{ include "puppetdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
