---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "puppetdb.fullname" . }}-initscripts
data:
  configuressl.sh: |
    # activate ssl for puppetdb
    sed -i '/^# ssl-/s/^# //g' /etc/puppetlabs/puppetdb/conf.d/jetty.ini
