apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "puppetdb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "puppetdb.name" . }}
    helm.sh/chart: {{ include "puppetdb.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.puppetdb.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "puppetdb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "puppetdb.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.puppetdb.serviceAccountName }}
      serviceAccountName: {{ .Values.puppetdb.serviceAccountName }}
      {{- end }}
      {{- if .Values.puppetdb.image.pullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.puppetdb.image.pullSecrets | nindent  8 }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-autosign
          image: "{{ .Values.initContainersImage.repository }}:{{ .Values.initContainersImage.tag }}"
          imagePullPolicy: {{ .Values.initContainersImage.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - "psk=$(cat /run/secrets/autosign_psk); hostname=$(/opt/puppetlabs/bin/puppet config print certname | tr -d '\n'); echo \"custom_attributes:\n  1.2.840.113549.1.9.7: 'hashed;$(echo -n $psk/$hostname/puppetdb/production | openssl dgst -binary -sha256 | openssl base64)'\nextension_requests:\n  pp_role: 'puppetdb'\n  pp_environment: 'production'\" > /etc/puppetlabs/puppet/csr_attributes.yaml; /opt/puppetlabs/bin/puppet ssl submit_request --environment production --server {{ .Values.puppetdb.puppetServerURL }} --certificate_revocation=false --dns_alt_names='{{ include "puppetdb.fullname" . }},{{ .Values.puppetdb.public_name }}' --waitforcert 60 --confdir /etc/puppetlabs/puppet; cd /etc/puppetlabs/puppet/ssl && cp private_keys/$hostname.pem private_keys/puppetdb.pem && cp certs/$hostname.pem certs/puppetdb.pem ; mv /etc/puppetlabs/puppet/ssl/* /srv/puppetssl/"
          env:
            - name: HOME
              value: /tmp
          volumeMounts:
            - mountPath: /run/secrets/autosign_psk
              name: secrets
              subPath: autosign_psk
            - mountPath: /etc/puppetlabs/puppet
              name: confdir
            - mountPath: /srv/puppetssl
              name: ssldir
          resources:
            {{- toYaml .Values.puppetdb.init.autosign.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-jmx-exporter
          image: camptocamp/jmx-exporter:0.12.0
          command: [ "cp", "/jmx_prometheus_javaagent-0.12.0.jar", "/jmx-exporter/" ]
          volumeMounts:
            - mountPath: /jmx-exporter
              name: jmx-exporter
          resources:
            {{- toYaml .Values.puppetdb.init.jmx_exporter.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.puppetdb.securityContext | nindent 12 }}
          image: "{{ .Values.puppetdb.image.repository }}:{{ .Values.puppetdb.image.tag }}"
          imagePullPolicy: {{ .Values.puppetdb.image.pullPolicy }}
          env:
          {{- .Values.puppetdb.envs | nindent 12 }}
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
            - name: metrics
              containerPort: 9080
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/puppetlabs/server/data/puppetdb
              name: data
            - mountPath: /opt/puppetlabs/server/data/puppetdb/certs
              name: ssldir
            - mountPath: /etc/puppetlabs/puppetdb/pgsql/
              name: postgresql
            - mountPath: /jmx-exporter
              name: jmx-exporter
            - mountPath: /jmx-exporter/config.yaml
              name: jmx-exporter-config
              subPath: config.yaml
            - mountPath: /etc/puppetlabs/puppetdb/jolokia-access.xml
              name: jolokia
              subPath: jolokia-access.xml
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "curl --fail --resolve 'puppetdb:8080:127.0.0.1' 'http://puppetdb:8080/status/v1/services/puppetdb-status' | grep -q '\"state\":\"running\"'"
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.puppetdb.resources | nindent 12 }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 10 }}
      volumes:
        - name: jmx-exporter
          emptyDir: {}
        - name: data
        {{- if .Values.puppetdb.existingdataclaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.puppetdb.existingdataclaim }}
        {{ else }}
          emptyDir: {}
        {{ end }}
        - name: confdir
          emptyDir: {}
        - name: ssldir
          emptyDir: {}
        - name: secrets
          secret:
            secretName: {{ .Values.puppetdb.psk.existingSecret | default ( printf "%s" (include "puppetdb.fullname" . ))}}
        - name: postgresql
          configMap:
            name: {{ include "puppetdb.fullname" . }}-postgresql
        - name: jmx-exporter-config
          configMap:
            name: {{ include "puppetdb.fullname" . }}-jmx-exporter
        - name: jolokia
          configMap:
            name: {{ include "puppetdb.fullname" . }}-jolokia
      {{- with .Values.puppetdb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.puppetdb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.puppetdb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
