kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "tetragon-policy-builder.fullname" . }}
  labels:
    {{- include "tetragon-policy-builder.labels" . | nindent 4 }}
spec:
  policyTypes:
  - Ingress
  podSelector:
    matchLabels: {}
  ingress:
    - from:
        - podSelector: {}
