{
 "title": "💾 Postgres Database",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "prometheus" },
   { "name": "site", "query": { "query": "label_values(pg_static, site)" } },
   {
    "name": "database",
    "query": {
     "query": "label_values(pg_database_size_bytes{site=\"$site\"}, datname)"
    }
   },
   {
    "name": "focus_table",
    "label": "Table(s) picked for detailed analysis in \"Focus tables\" row",
    "query": {
     "query": "label_values(pg_stat_user_tables_idx_scan{datname=~\"$database\", site=\"$site\"}, relname)"
    }
   },
   {
    "name": "dbserver",
    "label": "Database server",
    "query": {
     "query": "label_values(pg_static{site=\"$site\"}, server)"
    }
   },
   {
    "name": "focus_query",
    "label": "QueryID for pg_stat_statements drill-down"
   },
   {
    "name": "pg_version",
    "query": {
     "query": "label_values(pg_static{site=\"$site\"}, short_version)"
    }
   },
   {
    "name": "pg_master",
    "query": {
     "query": "query_result(pg_is_in_recovery{site=\"$site\"} == 0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_is_in_recovery{server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Transaction rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{datname!~\"(template|postgres|rdsadmin).*\",server=~\"$dbserver\"}[$__rate_interval]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{datname!~\"(template|postgres|rdsadmin).*\",server=~\"$dbserver\"}[$__rate_interval]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Top10 rows touched by INSERTs/UPDATEs per table",
   "type": "bargauge",
   "description": "master only",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (relname,datname) (rate(pg_stat_user_tables_n_tup_ins{site=\"$site\", server=\"$pg_master\"}[$__rate_interval])))",
     "legendFormat": "{{datname}}/{{relname}} INSERTs"
    },
    {
     "expr": "topk(5, sum by (relname,datname) (rate(pg_stat_user_tables_n_tup_upd{site=\"$site\", server=\"$pg_master\"}[$__rate_interval])))",
     "legendFormat": "{{datname}}/{{relname}} UPDATEs"
    }
   ]
  },
  {
   "title": "PostgreSQL Uptime",
   "type": "stat",
   "description": "Postgres server Uptime",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{server=~\"$dbserver\"} * 1000",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Most written tables",
   "type": "magnesium-wordcloud-panel",
   "description": "writes/s, instant, master only",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 4 },
   "targets": [
    {
     "expr": "topk(25, sum(rate(pg_stat_user_tables_n_tup_ins{server=\"$pg_master\"}[5m]) + rate(pg_stat_user_tables_n_tup_upd{server=\"$pg_master\"}[5m]) + rate(pg_stat_user_tables_n_tup_del{server=\"$pg_master\"}[5m])) by (relname))"
    }
   ]
  },
  {
   "title": "Top10 table seq scan rates",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "scan/s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (relname,datname) (rate(pg_stat_user_tables_seq_scan{site=\"$site\"}[$__rate_interval])))",
     "legendFormat": "{{datname}}/{{relname}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "pg_static{server=~\"$dbserver\"}"
    }
   ]
  },
  {
   "title": "%cache usage",
   "type": "gauge",
   "description": "storage IO blocks hit/miss ratio",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "avg by (server) (rate(pg_stat_database_blks_hit{server=~\"$dbserver\", datname=~\"$database\"}[$__rate_interval])) / avg by (server) (rate(pg_stat_database_blks_hit{server=~\"$dbserver\", datname=~\"$database\"}[$__rate_interval]) + rate(pg_stat_database_blks_read{server=~\"$dbserver\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Global fragmentation",
   "type": "stat",
   "description": "ratio dead / total rows",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_dead_tup{site=\"$site\", datname=~\"$database\", server=\"$pg_master\"}) / (sum(pg_stat_user_tables_n_live_tup{site=\"$site\", datname=~\"$database\", server=\"$pg_master\"}) + sum(pg_stat_user_tables_n_dead_tup{site=\"$site\", datname=~\"$database\", server=\"$pg_master\"}))"
    }
   ]
  },
  {
   "title": "Most read tables",
   "type": "magnesium-wordcloud-panel",
   "description": "sed + idx reads/s, instant, selected server(s)",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "topk(25, sum(rate(pg_stat_user_tables_idx_tup_fetch{site=\"$site\"}[5m]) + rate(pg_stat_user_tables_seq_tup_read{site=\"$site\"}[5m])) by (relname))"
    }
   ]
  },
  {
   "title": "Top10 table idx scan rates",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "scan/s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (relname,datname) (rate(pg_stat_user_tables_idx_scan{site=\"$site\"}[$__rate_interval])))",
     "legendFormat": "{{datname}}/{{relname}}"
    }
   ]
  },
  {
   "title": "% client connected",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (server) (pg_stat_database_numbackends{server=~\"$dbserver\"})) / on(server) (sum by (server) (pg_settings_max_connections{server=~\"$dbserver\"}))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Conflict/Deadlock",
   "type": "stat",
   "description": "Maximum count over sliding 10m window",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"pg_stat_database_(deadlocks|conflicts).*\",server=~\"$dbserver\"}) - sum({__name__=~\"pg_stat_database_(deadlocks|conflicts).*\",server=~\"$dbserver\"} offset 10m)"
    }
   ]
  },
  { "title": "Activity by Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "DB Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "repeat": "node",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size_bytes{site=\"$site\", server=\"$pg_master\", datname=~\"$database\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Table scans per DB",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "seq scans/s" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_user_tables_seq_scan{site=\"$site\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "seq scan {{datname}}"
    },
    {
     "expr": "sum by (datname) (rate(pg_stat_user_tables_seq_tup_read{site=\"$site\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "seq tuple read {{datname}}"
    }
   ]
  },
  {
   "title": "Index scans per DB",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "index scans/s" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_user_tables_idx_scan{site=\"$site\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "index scan {{datname}}"
    },
    {
     "expr": "sum by (datname) (rate(pg_stat_user_tables_idx_tup_fetch{site=\"$site\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "index tuple fetch {{datname}}"
    }
   ]
  },
  {
   "title": "Write ops rate per DB",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "rows/s" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_user_tables_n_tup_ins{site=\"$site\", datname=~\"$database\"}[2m]) or rate(pg_stat_user_tables_light_n_tup_ins{site=\"$site\", datname=~\"$database\"}[2m]))",
     "legendFormat": "Tuple inserted on {{datname}}"
    },
    {
     "expr": "sum by (datname) (rate(pg_stat_user_tables_n_tup_upd{site=\"$site\", datname=~\"$database\"}[2m]) or rate(pg_stat_user_tables_light_n_tup_upd{site=\"$site\", datname=~\"$database\"}[2m]))",
     "legendFormat": "Tuple updated on {{datname}}"
    },
    {
     "expr": "sum by (datname) (rate(pg_stat_user_tables_n_tup_del{site=\"$site\", datname=~\"$database\"}[2m]) or rate(pg_stat_user_tables_light_n_tup_del{site=\"$site\", datname=~\"$database\"}[2m]))",
     "legendFormat": "Tuple deleted on {{datname}}"
    },
    {
     "expr": "sum by (datname) (rate(pg_stat_user_tables_n_tup_hot_upd{site=\"$site\", datname=~\"$database\"}[2m]) or rate(pg_stat_user_tables_light_n_tup_hot_upd{site=\"$site\", datname=~\"$database\"}[2m]))",
     "legendFormat": "Tuple hot updated on {{datname}}"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Longest transaction",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{server=~\"$dbserver\", datname=~\"$database\"} > 0",
     "legendFormat": "{{state}} on {{server}}/{{datname}}"
    }
   ]
  },
  {
   "title": "Write ops rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "rows/s" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (rate(pg_stat_user_tables_n_tup_ins{server=~\"dbserver\", datname=~\"$database\"}[$__rate_interval])) > 0",
     "legendFormat": "Tuple inserted on {{server}}"
    },
    {
     "expr": "sum by (server) (rate(pg_stat_user_tables_n_tup_upd{server=~\"$dbserver\", datname=~\"$database\"}[$__rate_interval])) > 0",
     "legendFormat": "Tuple updated on {{server}}"
    },
    {
     "expr": "sum by (server) (rate(pg_stat_user_tables_n_tup_del{server=~\"$dbserver\", datname=~\"$database\"}[$__rate_interval])) > 0",
     "legendFormat": "Tuple deleted on {{server}}"
    },
    {
     "expr": "sum by (server) (rate(pg_stat_user_tables_n_tup_hot_upd{server=~\"$dbserver\", datname=~\"$database\"}[$__rate_interval])) > 0",
     "legendFormat": "Tuple hot updated on {{server}}"
    }
   ]
  },
  {
   "title": "Table fragmentation (only master server)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 }
  },
  {
   "title": "Rows added/removed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "rows" }
   ],
   "targets": [
    {
     "expr": "(sum(pg_stat_user_tables_n_live_tup{server=\"$pg_master\", datname=~\"$database\"}) by (relname,datname)) - (sum(pg_stat_user_tables_n_live_tup{server=\"$pg_master\", datname=~\"$database\"} offset $__interval) by (relname,datname)) != 0",
     "legendFormat": "{{datname}} {{relname}}"
    }
   ]
  },
  {
   "title": "Top25 & total dead tuples, VACUUM/ANALYZE activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "rows" }
   ],
   "targets": [
    {
     "expr": "topk(25, sum(pg_stat_user_tables_n_dead_tup{server=\"$pg_master\", datname=~\"$database\"}) by (datname, schemaname, relname))",
     "legendFormat": "{{datname}} {{schemaname}}.{{relname}}"
    },
    {
     "expr": "sum(pg_stat_user_tables_n_dead_tup{server=\"$pg_master\", datname=~\"$database\"})",
     "legendFormat": "Total dead tuples"
    },
    {
     "expr": "rate(pg_stat_user_tables_autovacuum_count{server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]) > 0",
     "legendFormat": "auto vacuum {{datname}} {{schemaname}}.{{relname}}"
    },
    {
     "expr": "rate(pg_stat_user_tables_vacuum_count{server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]) > 0",
     "legendFormat": "vacuum {{datname}} {{schemaname}}.{{relname}}"
    },
    {
     "expr": "rate(pg_stat_user_tables_analyze_count{server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]) > 0",
     "legendFormat": "analyze {{datname}} {{schemaname}}.{{relname}}"
    },
    {
     "expr": "rate(pg_stat_user_tables_autoanalyze_count{server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]) > 0",
     "legendFormat": "auto analyze {{datname}} {{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Top5 modif rate since last ANALYZE",
   "type": "graph",
   "description": "Only tables with > 1000 records",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "none", "label": "rows/s" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(pg_stat_user_tables_n_mod_since_analyze{server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]) > 0) by (relname,schemaname,datname))",
     "legendFormat": "{{datname}} {{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Most fragmented Tables",
   "type": "graph",
   "description": "Only tables with > 1000 records",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(25,sum(((pg_stat_user_tables_n_dead_tup{server=\"$pg_master\", datname=~\"$database\"} > 0) / (pg_stat_user_tables_n_live_tup{server=\"$pg_master\", datname=~\"$database\"} + pg_stat_user_tables_n_dead_tup{server=\"$pg_master\", datname=~\"$database\"} > 0))) by (relname,schemaname,datname))",
     "legendFormat": "{{datname}} {{schemaname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Tables Statistics",
   "type": "table",
   "description": "Only tables with > 1000 records",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup{server=\"$pg_master\", datname=~\"$database\"}) by (relname, schemaname,datname)"
    },
    {
     "expr": "sum(pg_stat_user_tables_n_dead_tup{server=\"$pg_master\", datname=~\"$database\"}) by (relname, schemaname,datname)"
    },
    {
     "expr": "sum(pg_stat_user_tables_n_mod_since_analyze{server=\"$pg_master\", datname=~\"$database\"}) by (relname, schemaname, datname)"
    },
    {
     "expr": "sum(pg_stat_user_tables_last_autovacuum{server=\"$pg_master\", datname=~\"$database\"}) by (relname, schemaname,datname) * 1000"
    },
    {
     "expr": "sum(pg_stat_user_tables_last_vacuum{server=\"$pg_master\", datname=~\"$database\"}) by (relname, schemaname,datname) * 1000"
    },
    {
     "expr": "sum(pg_stat_user_tables_last_autoanalyze{server=\"$pg_master\", datname=~\"$database\"}) by (relname, schemaname,datname) * 1000"
    },
    {
     "expr": "sum(pg_stat_user_tables_last_analyze{server=\"$pg_master\", datname=~\"$database\"}) by (relname, schemaname,datname) * 1000"
    },
    {
     "expr": "sum(((pg_stat_user_tables_n_dead_tup{server=\"$pg_master\", datname=~\"$database\"} > 0)/ (pg_stat_user_tables_n_live_tup{server=\"$pg_master\"} > 0) )* 100) by (relname,schemaname,datname)",
     "legendFormat": "fragmentation"
    }
   ]
  },
  { "title": "Focus tables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Table scans",
   "type": "graph",
   "description": "Sum accross selected servers",
   "gridPos": { "h": 17, "w": 6, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "seq scans/s" }
   ],
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_seq_scan{relname=~\"$focus_table\",site=\"$site\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "seq scan {{relname}}"
    },
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_seq_tup_read{relname=~\"$focus_table\",site=\"$site\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "seq tuple read {{relname}}"
    }
   ]
  },
  {
   "title": "Index scans",
   "type": "graph",
   "description": "Sum accross selected servers",
   "gridPos": { "h": 17, "w": 6, "x": 6, "y": 93 },
   "yaxes": [
    { "format": "short", "label": "index scans/s" }
   ],
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_idx_scan{relname=~\"$focus_table\",site=~\"$site\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "index scan {{relname}}"
    },
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_idx_tup_fetch{relname=~\"$focus_table\",site=~\"$site\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "index tuple fetch {{relname}}"
    }
   ]
  },
  {
   "title": "Write ops rate",
   "type": "graph",
   "description": "Master server only",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_n_tup_ins{relname=~\"$focus_table\",server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval])) + sum by (relname) (rate(pg_stat_user_tables_n_tup_upd{relname=~\"$focus_table\",server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval])) + sum by (relname) (rate(pg_stat_user_tables_n_tup_del{relname=~\"$focus_table\",server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval])) + sum by (relname) (rate(pg_stat_user_tables_n_tup_hot_upd{relname=~\"$focus_table\",server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} Total"
    },
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_n_tup_ins{relname=~\"$focus_table\",server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} inserts"
    },
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_n_tup_upd{relname=~\"$focus_table\",server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} updates"
    },
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_n_tup_hot_upd{relname=~\"$focus_table\",server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} hot updates"
    },
    {
     "expr": "sum by (relname) (rate(pg_stat_user_tables_n_tup_del{relname=~\"$focus_table\",server=\"$pg_master\", datname=~\"$database\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} deletes"
    }
   ]
  },
  {
   "title": "Focus Tables live/dead tuples ratio (fragmentation) + VACUUM/ANALYZE activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 93 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(((pg_stat_user_tables_n_dead_tup{server=\"$pg_master\", relname=~\"$focus_table\", datname=~\"$database\"} > 0)/ (pg_stat_user_tables_n_live_tup{server=\"$pg_master\", relname=~\"$focus_table\", datname=~\"$database\"} > 0) )* 100) by (relname,schemaname,datname)",
     "legendFormat": "{{datname}} {{schemaname}}.{{relname}} fragmentation %"
    },
    {
     "expr": "pg_stat_user_tables_n_dead_tup{server=\"$pg_master\", relname=~\"$focus_table\", datname=~\"$database\"} /\n(\n    (pg_stat_user_tables_n_live_tup{server=\"$pg_master\", relname=~\"$focus_table\", datname=~\"$database\"} *\n     ignoring (datname,relname,schemaname) group_left (server) pg_settings_autovacuum_vacuum_scale_factor{server=\"$pg_master\"}\n    ) + ignoring (datname,relname,schemaname) group_left (server) pg_settings_autovacuum_vacuum_threshold{server=\"$pg_master\"}\n) * 100",
     "legendFormat": "{{datname}} {{schemaname}}.{{relname}} maintenance  needed %"
    },
    {
     "expr": "pg_stat_user_tables_vacuum_count{server=\"$pg_master\",relname=~\"$focus_table\", datname=~\"$database\"} - (pg_stat_user_tables_vacuum_count{server=\"$pg_master\",relname=~\"$focus_table\", datname=~\"$database\"} offset $__interval)",
     "legendFormat": "vacuum {{relname}}"
    },
    {
     "expr": "pg_stat_user_tables_autovacuum_count{server=\"$pg_master\",relname=~\"$focus_table\", datname=~\"$database\"} - (pg_stat_user_tables_autovacuum_count{server=\"$pg_master\",relname=~\"$focus_table\", datname=~\"$database\"} offset $__interval)",
     "legendFormat": "autovacuum {{relname}}"
    },
    {
     "expr": "pg_stat_user_tables_autoanalyze_count{server=\"$pg_master\",relname=~\"$focus_table\", datname=~\"$database\"} - (pg_stat_user_tables_autoanalyze_count{server=\"$pg_master\",relname=~\"$focus_table\", datname=~\"$database\"} offset $__interval)",
     "legendFormat": "autoanalyze {{relname}}"
    },
    {
     "expr": "pg_stat_user_tables_analyze_count{server=\"$pg_master\",relname=~\"$focus_table\", datname=~\"$database\"} - (pg_stat_user_tables_analyze_count{server=\"$pg_master\",relname=~\"$focus_table\", datname=~\"$database\"} offset $__interval)",
     "legendFormat": "analyze {{relname}}"
    }
   ]
  },
  {
   "title": "IO %cache usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_statio_user_tables_idx_blks_hit{relname=~\"$focus_table\", datname=~\"$database\", site=\"$site\"}[$__rate_interval])) by (relname)  / (sum(rate(pg_statio_user_tables_idx_blks_hit{relname=~\"$focus_table\", datname=~\"$database\", site=\"$site\"}[$__rate_interval])) by (relname) + sum(rate(pg_statio_user_tables_idx_blks_read{relname=~\"$focus_table\", datname=~\"$database\", site=\"$site\"}[$__rate_interval])) by (relname))",
     "legendFormat": "{{relname}} idx"
    },
    {
     "expr": "sum(rate(pg_statio_user_tables_heap_blks_hit{relname=~\"$focus_table\", datname=~\"$database\", site=\"$site\"}[$__rate_interval])) by (relname)  / (sum(rate(pg_statio_user_tables_heap_blks_hit{relname=~\"$focus_table\", datname=~\"$database\", site=\"$site\"}[$__rate_interval])) by (relname) + sum(rate(pg_statio_user_tables_heap_blks_read{relname=~\"$focus_table\", datname=~\"$database\", site=\"$site\"}[$__rate_interval])) by (relname))",
     "legendFormat": "{{relname}} heap"
    }
   ]
  },
  { "title": "Badly performing statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Most frequent queries (5 worst by server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "label_replace(topk(5, rate(pg_stat_statements_most_frequent_calls{site=\"$site\"}[$__rate_interval])) by (server), \"short_name\", \"$1\", \"server\", \"([^\\\\.]+)\\\\..+\")",
     "legendFormat": "{{short_name}}/{{datname}}: {{queryid}} ({{shrunk_query_text}})"
    }
   ]
  },
  {
   "title": "Total time spent during last 10min (5 worst by server)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 111 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(topk(5, (pg_stat_statements_total_time_total_time_seconds{site=\"$site\"} - (pg_stat_statements_total_time_total_time_seconds{site=\"$site\"} offset 10m))) by (server), \"short_name\", \"$1\", \"server\", \"([^\\\\.]+)\\\\..+\")",
     "legendFormat": "{{short_name}}/{{datname}}: {{queryid}} ({{shrunk_query_text}})"
    }
   ]
  },
  {
   "title": "Queries triggering temporary files (work_mem overflow)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 111 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(pg_stat_statements_temp_files_temp_blks_read{site=\"$site\",shrunk_query_text!~\"SELECT.+queryid,.+\"}[$__rate_interval]) > 0, \"short_name\", \"$1\", \"server\", \"([^\\\\.]+)\\\\..+\")",
     "legendFormat": "reads {{short_name}}/{{datname}}: {{queryid}} ({{shrunk_query_text}})"
    },
    {
     "expr": "label_replace(rate(pg_stat_statements_temp_files_temp_blks_written{server=\"$site\",shrunk_query_text!~\"SELECT.+queryid,.+\"}[$__rate_interval]) * -1 < 0, \"short_name\", \"$1\", \"server\", \"([^\\\\.]+)\\\\..+\")",
     "legendFormat": "writes {{short_name}}/{{datname}}: {{queryid}} ({{shrunk_query_text}})"
    }
   ]
  },
  {
   "title": "Slowest single queries (5 worst by server)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, label_replace(pg_stat_statements_max_time_max_time_seconds{server=~\"$dbserver\"}, \"short_name\", \"$1\", \"server\", \"([^\\\\.]+)\\\\..+\")) by (server)",
     "legendFormat": "{{short_name}}/{{datname}}: {{queryid}} ({{shrunk_query_text}})"
    }
   ]
  },
  {
   "title": "Single queries returning the most rows per call (5 worst by server)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "rows" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(topk(5, pg_stat_statements_most_rows_rows{server=~\"$dbserver\"} / pg_stat_statements_most_rows_calls{server=~\"$dbserver\"}) by (server), \"short_name\", \"$1\", \"server\", \"([^\\\\.]+)\\\\..+\")",
     "legendFormat": "{{short_name}}/{{datname}}: {{queryid}} ({{shrunk_query_text}})"
    }
   ]
  },
  {
   "title": "Drilldown on query ID \"$focus_query\"",
   "type": "graph",
   "description": "For full details run:\nSELECT * from pg_stat_statements WHERE queryid='$focus_query';",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "ops", "label": "queries/s" }
   ],
   "targets": [
    {
     "expr": "max(rate(label_replace({__name__=~\"pg_stat_statements_.+_calls\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")[$__rate_interval:$__interval])) by (queryid,shrunk_query_text)",
     "legendFormat": "request rate: {{shrunk_query_text}}[...]"
    },
    {
     "expr": "max(rate(label_replace({__name__=~\"pg_stat_statements_.+_rows\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")[$__rate_interval:$__interval])) by (queryid,shrunk_query_text)",
     "legendFormat": "rows returned: {{shrunk_query_text}}[...]"
    }
   ]
  },
  {
   "title": "Drilldown on query ID \"$focus_query\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 133 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "max(rate(label_replace({__name__=~\"pg_stat_statements_.+_blks_read\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")[$__rate_interval:$__interval])) by (queryid,shrunk_query_text)",
     "legendFormat": "IO reads: {{shrunk_query_text}}[...]"
    },
    {
     "expr": "(max(rate(label_replace({__name__=~\"pg_stat_statements_.+_blks_read\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")[$__rate_interval:$__interval])) by (queryid,shrunk_query_text)) * -1",
     "legendFormat": "IO writes: {{shrunk_query_text}}[...]"
    }
   ]
  },
  {
   "title": "Drilldown on query ID \"$focus_query\"",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(label_replace({__name__=~\"pg_stat_statements_.+_max_time_seconds\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")) by (queryid)",
     "legendFormat": "max resp. time"
    },
    {
     "expr": "min(label_replace({__name__=~\"pg_stat_statements_.+_min_time_seconds\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")) by (queryid)",
     "legendFormat": "min resp. time"
    },
    {
     "expr": "avg(label_replace({__name__=~\"pg_stat_statements_.+_mean_time_seconds\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")) by (queryid)",
     "legendFormat": "mean resp. time"
    },
    {
     "expr": "avg(label_replace({__name__=~\"pg_stat_statements_.+_stddev_time_seconds\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")) by (queryid)",
     "legendFormat": "resp. time stddev"
    },
    {
     "expr": "max(label_replace({__name__=~\"pg_stat_statements_.+_blk_read_time_seconds\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\") - label_replace({__name__=~\"pg_stat_statements_.+_blk_read_time_seconds\",queryid=\"$focus_query\"} offset 10m, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")) by (queryid)",
     "legendFormat": "IO read time over last 10min"
    },
    {
     "expr": "max(label_replace({__name__=~\"pg_stat_statements_.+_blk_write_time_seconds\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\") - label_replace({__name__=~\"pg_stat_statements_.+_blk_write_time_seconds\",queryid=\"$focus_query\"} offset 10m, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")) by (queryid)",
     "legendFormat": "IO write time over last 10min"
    },
    {
     "expr": "max(label_replace({__name__=~\"pg_stat_statements_.+_total_time_seconds\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\") - label_replace({__name__=~\"pg_stat_statements_.+_total_time_seconds\",queryid=\"$focus_query\"} offset 10m, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")) by (queryid)",
     "legendFormat": "total time over last 10min"
    },
    {
     "expr": "max(label_replace({__name__=~\"pg_stat_statements_.+_rows\",queryid=\"$focus_query\"}, \"metric_name_subset\", \"$1\", \"__name__\", \"pg_stat_statements_(.+)_rows\") / label_replace({__name__=~\"pg_stat_statements_.+_calls\",queryid=\"$focus_query\"}, \"metric_name_subset\", \"$1\", \"__name__\", \"pg_stat_statements_(.+)_calls\")) by (queryid)",
     "legendFormat": "avg rows/call"
    },
    {
     "expr": "max(label_replace({__name__=~\"pg_stat_statements_.+_calls\",queryid=\"$focus_query\"}, \"metric_name\", \"$1\", \"__name__\", \"(.+)\") - label_replace({__name__=~\"pg_stat_statements_.+_calls\",queryid=\"$focus_query\"} offset 10m, \"metric_name\", \"$1\", \"__name__\", \"(.+)\")) by (queryid)",
     "legendFormat": "#calls over last 10min"
    }
   ]
  },
  { "title": "Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "Connected clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (server) (pg_stat_database_numbackends{server=~\"$dbserver\"})",
     "legendFormat": "{{server}} (current)"
    },
    {
     "expr": "min(pg_settings_max_connections{server=~\"$dbserver\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Connected clients per DB (main & replicas)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_database_numbackends{server=~\"$dbserver\", datname=~\"$database\"}) > 0",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "sum(pg_settings_max_connections{server=~\"$dbserver\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Clients connected to $dbserver",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 151 },
   "repeat": "dbserver",
   "yaxes": [
    { "format": "short", "label": "conn. per client" }
   ],
   "targets": [
    {
     "expr": "sum(pg_client_connections_count{server=~\"$dbserver\"}) by (appname, client_addr)",
     "legendFormat": "{{client_addr}}: {{appname}}"
    }
   ]
  },
  {
   "title": "Client memory usage ($dbserver)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 158 },
   "repeat": "dbserver",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{site=\"$site\", server=~\"$dbserver\"} * pg_settings_max_connections{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "work_mem * max_conns"
    },
    {
     "expr": "max by (server) (pg_settings_work_mem_bytes{site=\"$site\", server=~\"$dbserver\"}) * (count by (server) (pg_stat_database_numbackends{site=\"$site\",server=~\"$dbserver\"}))",
     "legendFormat": "work * current_connections"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "Lag between master and last replica (xlog diff)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(pg_xlog_position{site=\"$site\"}) - min(pg_xlog_position{site=\"$site\"})"
    },
    { "expr": "1000000000", "legendFormat": "Alert" }
   ]
  },
  {
   "title": "Lag on replica (seconds) slave point of view",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 167 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pg_replication_replag{site=\"$site\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Lag on replica (Bytes) master point of view",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 167 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_replication_replay_lag{site=\"$site\"}",
     "legendFormat": "{{client_addr}}"
    }
   ]
  },
  {
   "title": "Xlog position",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 167 },
   "yaxes": [
    { "format": "hex" }
   ],
   "targets": [
    {
     "expr": "pg_xlog_position{site=\"$site\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 179 }, "repeat": "dbserver", "options": { "content": "# ${dbserver}" } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 181 },
   "repeat": "dbserver",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_is_in_recovery{site=\"$site\", server=~\"$dbserver\"}"
    }
   ]
  },
  {
   "title": "Wal segment count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 184 },
   "repeat": "dbserver",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_wals_count{site=\"$site\",server=~\"$dbserver\"}",
     "legendFormat": "count"
    },
    {
     "expr": "pg_wals_size{site=\"$site\",server=~\"$dbserver\"}",
     "legendFormat": "size"
    }
   ]
  },
  { "title": "Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 190 } },
  {
   "title": "Temporary tables (work_mem overflow)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_temp_bytes{site=\"$site\"}[$__rate_interval]) > 0",
     "legendFormat": "Temp bytes {{server}} DB:{{datname}}"
    },
    {
     "expr": "rate(pg_stat_database_temp_files{site=\"$site\"}[$__rate_interval]) > 0",
     "legendFormat": "Temp files {{server}} DB:{{datname}}"
    }
   ]
  },
  {
   "title": "Lock / Conflicts",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 191 },
   "yaxes": [
    { "format": "short", "label": "locks/s" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_deadlocks{server=~\"$dbserver\", datname=~\"$database\"}[$__rate_interval])",
     "legendFormat": "Deadlock {{datname}} {{server}}"
    },
    {
     "expr": "rate(pg_stat_database_conflicts{server=~\"$dbserver\", datname=~\"$database\"}[$__rate_interval])",
     "legendFormat": "Conflicts {{datname}} {{server}}"
    },
    {
     "expr": "max by (mode, datname, server) (rate(pg_locks_count{server=~\"$dbserver\", datname=~\"$database\"}[$__rate_interval])) > 0",
     "legendFormat": "{{mode}} {{datname}} {{server}}"
    }
   ]
  },
  {
   "title": "Workers state",
   "type": "graph",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 191 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{server=~\"$dbserver\", datname=~\"$database\"}) by (datname, server, state) > 0",
     "legendFormat": "{{state}} on {{server}}/{{datname}}"
    }
   ]
  },
  {
   "title": "Background writer: checkpoints",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pg_stat_bgwriter_checkpoints_timed{server=~\"$dbserver\"} - (pg_stat_bgwriter_checkpoints_timed{server=~\"$dbserver\"} offset $__interval)",
     "legendFormat": "scheduled checkpoints: {{server}}"
    },
    {
     "expr": "pg_stat_bgwriter_checkpoints_req{server=~\"$dbserver\"} - (pg_stat_bgwriter_checkpoints_req{server=~\"$dbserver\"} offset $__interval)",
     "legendFormat": "requested checkpoints: {{server}}"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{server=~\"$dbserver\"}[$__rate_interval])",
     "legendFormat": "write time rate: {{server}}"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{server=~\"$dbserver\"}[$__rate_interval])",
     "legendFormat": "sync time rate: {{server}}"
    }
   ]
  },
  {
   "title": "Background writer: buffer allocations per type",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 206 },
   "yaxes": [
    { "format": "short", "label": "buffers allocated/s" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_buffers_backend{server=~\"$dbserver\"}[$__rate_interval])",
     "legendFormat": "backend: {{server}}"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{server=~\"$dbserver\"}[$__rate_interval])",
     "legendFormat": "alloc: {{server}}"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{server=~\"$dbserver\"}[$__rate_interval])",
     "legendFormat": "fsync: {{server}}"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{server=~\"$dbserver\"}[$__rate_interval])",
     "legendFormat": "checkpoint: {{server}}"
    },
    {
     "expr": "rate(pg_stat_bgwriter_buffers_clean{server=~\"$dbserver\"}[$__rate_interval])",
     "legendFormat": "clean: {{server}}"
    }
   ]
  },
  {
   "title": "Database total rows count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup{server=\"$pg_master\"})"
    }
   ]
  },
  {
   "title": "Memory usage breakdown ($dbserver)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 216 },
   "repeat": "dbserver",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{server=~\"$dbserver\"}",
     "legendFormat": "shared_buffers"
    },
    {
     "expr": "pg_settings_effective_cache_size_bytes{server=~\"$dbserver\"}",
     "legendFormat": "effective_cache_size"
    },
    {
     "expr": "pg_settings_work_mem_bytes{server=~\"$dbserver\"} * pg_settings_max_connections{server=~\"$dbserver\"}",
     "legendFormat": "work_mem * max_conns"
    },
    {
     "expr": "sum(pg_settings_work_mem_bytes{server=~\"$dbserver\"}) * sum(pg_stat_database_numbackends{server=~\"$dbserver\"})",
     "legendFormat": "work_mem * current_conns"
    },
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{server=~\"$dbserver\"}",
     "legendFormat": "maintenance_work_mem"
    }
   ]
  },
  { "title": "Postgres Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 224 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 225 }, "repeat": "dbserver", "options": { "content": "# ${dbserver}" } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 227 },
   "repeat": "dbserver",
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_is_in_recovery{site=\"$site\", server=~\"$dbserver\"}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 230 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max WAL size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 233 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Shared Buffer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 236 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Effective cache size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 239 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Maintenance work mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 242 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Work mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 245 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Standby Streaming Delay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 248 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_standby_streaming_delay_seconds{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Standby Archive Delay",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 251 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_standby_archive_delay_seconds{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Random page cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 254 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Sequential page cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 257 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Worker",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 260 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Max Parallel Worker",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 263 },
   "repeat": "dbserver",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{site=\"$site\", server=~\"$dbserver\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}