apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "imap-mailbox-exporter.fullname" . }}
  labels:
    app: {{ template "imap-mailbox-exporter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "imap-mailbox-exporter.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.internalPort }}
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: {{ .Values.service.internalPort }}
          env:
            - name: IMAP_SERVER
              value: {{ .Values.imap.server }}
            - name: IMAP_USERNAME
              value: {{ .Values.imap.username }}
            - name: IMAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.imap.passwordSecret }}
                  key: password
            - name: IMAP_MAILBOX
              value: {{ .Values.imap.mailbox }}
            - name: IMAP_QUERY_INTERVAL
              value: {{ .Values.imap.queryInterval | quote }}
            - name: LISTEN_ADDRESS
              value: {{ print ":" .Values.service.internalPort | quote }}
