{
 "title": "gitlab-s3-exporter",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "gitlab backup general info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "gitlab backup s3 file count",
   "type": "timeseries",
   "description": "counts how many backup file are stored for gitlab",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "s3_file_count{job=\"gitlab-s3-exporter\",namespace=\"gitlab\"}"
    }
   ]
  },
  {
   "title": "s3 exporter UP/DOWN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "up{container=\"s3-exporter\", endpoint=\"http\", job=\"gitlab-s3-exporter\", namespace=\"gitlab\", service=\"gitlab-s3-exporter\"}"
    }
   ]
  },
  {
   "title": "s3 expoter cpu / second rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"s3-exporter\", endpoint=\"http\", job=\"gitlab-s3-exporter\", namespace=\"gitlab\", service=\"gitlab-s3-exporter\"}  [5m])"
    }
   ]
  },
  {
   "title": "latest backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "gitlab bacukp latest backup date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "s3_latest_file_timestamp{job=\"gitlab-s3-exporter\",namespace=\"gitlab\"}"
    }
   ]
  },
  {
   "title": "gitlab backup lastest file size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "s3_latest_file_size{job=\"gitlab-s3-exporter\",namespace=\"gitlab\"}"
    }
   ]
  },
  { "title": "oldest backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "gitlab bacukp oldest backup date",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "s3_oldest_file_timestamp{job=\"gitlab-s3-exporter\",namespace=\"gitlab\"}"
    }
   ]
  },
  {
   "title": "gitlab backup oldest file size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "s3_oldest_file_size{job=\"gitlab-s3-exporter\",namespace=\"gitlab\"}"
    }
   ]
  }
 ]
}