{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "s3-exporter.fullname" . }}
spec:
  endpoints:
  - port: http
    path: /probe
    params:
      bucket:
        - {{ .Values.s3.bucket }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "s3-exporter.labels" . | nindent 6 }}
{{- end }}

