{{ if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "s3-exporter.fullname" . }}
  labels:
    {{- include "s3-exporter.selectorLabels" . | nindent 8 }}
    {{- if .Values.servicemonitor.additionalLabels }}
    {{ toYaml .Values.servicemonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - port: http
    path: /metrics
    params:
      bucket:
        - {{ .Values.s3.bucket }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "s3-exporter.selectorLabels" . | nindent 6 }}
  {{ with .Values.servicemonitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{ end }}
{{ end }}

