{{- if .Values.init.psk }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-puppetdb-sd.fullname" $ }}
  labels:
    {{- include "prometheus-puppetdb-sd.labels" $ | nindent 4 }}
stringData:
  autosign_psk: {{ .Values.init.psk | quote }}
{{- end }}
