{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-puppetdb-sd.fullname" . }}
  labels:
    {{- include "prometheus-puppetdb-sd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "prometheus-puppetdb-sd.labels" . | nindent 4 }}
{{- end }}
