{{- if eq (index $.Values.prometheusPuppetdbSd.args "output.method") "k8s-secret" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-puppetdb-sd.fullname" $ }}
  labels:
    {{- include "prometheus-puppetdb-sd.labels" $ | nindent 4 }}
{{- end }}
