{{- if .Values.alertmanagerSnowPasswords }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snow-webhook.fullname" . }}
stringData:
  alertmanager-snow-passwords.yaml: {{ .Values.alertmanagerSnowPasswords | toYaml | indent 4}}
{{- end }}
