{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "puppet-catalog-diff-viewer.serviceAccountName" . }}
  labels:
{{ include "puppet-catalog-diff-viewer.labels" . | indent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end -}}
